version: "3"

volumes:
  proxy_logs:

services:
  proxy:
    depends_on:
      - leitunereguly
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./cert:/etc/letsencrypt"
      - "./dhparam:/var/cert/"

  leitunereguly:
    build:
      context: leitune-reguly
      dockerfile: Dockerfile
    volumes:
    - ./volumes/uploads:/srv/app/uploads
