version: "3"

volumes:
  proxy_logs:

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./cert:/etc/letsencrypt"

  leitunereguly:
    build:
      context: leitunereguly
      dockerfile: Dockerfile